backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/blog"
public_folder: "/assets/blog"
collections:
  - name: "partners"
    label: "Partners"
    folder: "src/partners"
    create: true
    fields:
      - { label: "Image caption", name: "imageAlt", widget: "string" }
      - { label: "Partners Image", name: "image", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["partners"] }
  - name: "clients"
    label: "Clients"
    folder: "src/clients"
    create: true
    fields:
      - { label: "Image caption", name: "imageAlt", widget: "string" }
      - { label: "Clients Image", name: "image", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["clients"] }
  - name: "services"
    label: "Services"
    folder: "src/services"
    create: true
    fields:
      - { label: "Href", name: "href", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Services Image", name: "image", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["services"] }
      - { label: "Image caption", name: "imageAlt", widget: "string" }
  - name: "applications"
    label: "Applications"
    folder: "src/applications"
    slug: "{{greenTitle}}"
    create: true
    fields:
      - { label: "Href", name: "href", widget: "string" }
      - { label: "Application Image", name: "image", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["applications"] }
      - { label: "Image caption", name: "imageAlt", widget: "string" }
      - { label: "GreenTitle", name: "greenTitle", widget: "string" }
      - { label: "NormalTitle", name: "normalTitle", widget: "string" }
      - { label: "BoldTitle", name: "boldTitle", widget: "string" }
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
